### PR TITLE
Digitalocean spaces adapter

### PR DESCRIPTION
**Pull request by lohanidamodar**
This PR, adds DoSpaces adapter which extends S3 adapter to easily support DigitalOcean Spaces storage.

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@eldadfux I have run the tests locally on my own spaces instance and everything is working.

**Comment by eldadfux** [comment]
Probably a good time to add a list of supported adapters on the README. I think you should also adjust the description of the repo on the top section of it.

**Comment by lohanidamodar** [comment]
@eldadfux I believe we can also have constants in Storage class regarding various supported device adapters, what do you think?

**Comment by eldadfux** [comment]
> @eldadfux I believe we can also have constants in Storage class regarding various supported device adapters, what do you think?

Good call!

**Comment by lohanidamodar** [comment]
@eldadfux have made the requested updates

**Pull request merged**
