### PR TITLE
Scality storage adapter

### PR DESCRIPTION
**Pull request by misantron**
Closes https://github.com/appwrite/appwrite/issues/3987

### CODE REVIEW

**Comment by misantron** [comment]
What is the point of using `"minimum-stability": "dev"` at Composer config?

**Comment by christyjacob4** [comment]
Please sync your branch with `main` . It has fixes for the failing CI tests

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by misantron** [comment]
First of all Scality credentials required for passing the tests.

**Comment by misantron** [comment]
Scality can be self-hosted or using public cloud as a backend. That's why we need to pass host to adapter. In some other PR I saw that you don't want to change constructor signature. How should I do this? Thanks.

**Comment by stnguyen90** [comment]
> Scality can be self-hosted or using public cloud as a backend. That's why we need to pass host to adapter. In some other PR I saw that you don't want to change constructor signature. How should I do this? Thanks.

@christyjacob4, thoughts on this?

**Comment by christyjacob4** [comment]
@misantron thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

Regarding the host issue, I believe its creating a limitation for self hosted instances of other storage adapters as well. 

How about we pass an optional `?string $host` parameter to the constructor and use it to override the default behaviour?

**Pull request closed without merging**
