### PR TITLE
Fix : Linode File Upload

### PR DESCRIPTION
**Pull request by everly-gif**
### Trim extra slashes before passing root.
Doing this because it creates an extra `/` while integrating with Appwrite.
for eg , a call as below was being made.

`https://<bucket-name>.eu-central-1.linodeobjects.com**//**storage/uploads/app-630cd8d7a106aa302d27/630cd8e90d3b33e8ff5c/6/3/0/c/630cdc2875416374d993.jpg`

The root  within Appwrite are already prefixed with  `/` (seen as  below). Hence, we need to trim it here to avoid double slashes.

This PR implements trimming the root in the constructor.
```php
const APP_STORAGE_UPLOADS = '/storage/uploads';
const APP_STORAGE_FUNCTIONS = '/storage/functions';
const APP_STORAGE_BUILDS = '/storage/builds';
const APP_STORAGE_CACHE = '/storage/cache';
const APP_STORAGE_CERTIFICATES = '/storage/certificates';
const APP_STORAGE_CONFIG = '/storage/config';
```

### CODE REVIEW

**Comment by stnguyen90** [comment]
Could [this](https://github.com/utopia-php/storage/blob/eff78f96701daea2add807da52a0c8c6411b1d71/src/Storage/Device/S3.php#L232) be where the extra slash is being added in the beginning?

**Comment by everly-gif** [comment]
> Could [this](https://github.com/utopia-php/storage/blob/eff78f96701daea2add807da52a0c8c6411b1d71/src/Storage/Device/S3.php#L232) be where the extra slash is being added in the beginning?

yes, I believe so. I feel that's a better place to remove the slash , instead of trimming it. what do you think @lohanidamodar @eldadfux ?

**Comment by everly-gif** [comment]
Also the tests pass locally , they fail in Travis CI because of the expired credentials of various providers. Need help in updating them as I do not have access to it.

**Comment by christyjacob4** [comment]
Please sync your branch with `main` . It has fixes for the failing CI tests

**Comment by christyjacob4** [comment]
@everly-gif we also need to do the same thing for the `Local` adapter

**Review by christyjacob4 — APPROVED** [review]

**Review by lohanidamodar — APPROVED** [review]
Looks good.

**Pull request merged**
