### PR TITLE
Fix s3 refactor

### PR DESCRIPTION
**Pull request by eldadfux**
Fixed AWS S3 tests
Removed code leftovers
Code refactoring
All exceptions are handled with the HTTP response
(Almost) All errors are handled with exceptions

### CODE REVIEW

**Review by lohanidamodar — APPROVED** [review]
Looks solid, clean! Feels like i did not spend enough time refactoring. Will remember it for next time :smile:

**Review by lohanidamodar — APPROVED** [review]
Looks good to me, but we need to research more on how to optimize `move` function, its making 4 external requests, I couldn't yet find the proper way to optimize it.

**Comment by lohanidamodar** [comment]
@eldadfux ready to merge yet?

**Comment by eldadfux** [comment]
I have a few more ideas for improvement, but I can push them later

**Pull request merged**
