### PR TITLE
Google Cloud Storage Adapter

### PR DESCRIPTION
**Pull request by eigengravy**
Closes appwrite/appwrite#3994

### CODE REVIEW

**Comment by christyjacob4** [comment]
Please sync your branch with `main` . It has fixes for the failing CI tests

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by stnguyen90** [comment]
@eigengravy is this PR ready for review? Also, would you be able to provide some screenshots of the adapter working?

**Comment by eigengravy** [comment]
no, i haven't gotten the adapter working yet.

**Comment by christyjacob4** [comment]
@eigengravy closing the PR for now. Feel free to reopen it when you're ready to work on it again

**Pull request closed without merging**
